export enum FingerPrintScanStates{
    SCAN_FAILED,
    SCAN_SUCCESS,
    SCANNING,
    IDLE
}

export const WEBSOCKET_EVENTS={
    START_FINGERPRINT_SCAN:"START_FINGERPRINT_SCAN",
    SAVED_FINGERPRINT_SCAN:"SAVED_FINGERPRINT_SCAN",
    FINISH_FINGERPRINT_SCAN:"FINISH_FINGERPRINT_SCAN"
}
